UPDATE `items` SET `requiredlevel` = '30' WHERE `entry` = '1132';
UPDATE `items` SET `requiredlevel` = '30' WHERE `entry` = '33183';
UPDATE `items` SET `requiredlevel` = '30' WHERE `entry` = '2414';
UPDATE `items` SET `requiredlevel` = '30' WHERE `entry` = '29743';
UPDATE `items` SET `requiredlevel` = '30' WHERE `entry` = '29222';
UPDATE `items` SET `requiredlevel` = '30' WHERE `entry` = '28927';
UPDATE `items` SET `requiredlevel` = '30' WHERE `entry` = '8563';
UPDATE `items` SET `requiredlevel` = '30' WHERE `entry` = '13331';
UPDATE `items` SET `requiredlevel` = '30' WHERE `entry` = '33224';
UPDATE `items` SET `requiredlevel` = '30' WHERE `entry` = '8632';
UPDATE `items` SET `requiredlevel` = '30' WHERE `entry` = '8631';
UPDATE `items` SET `requiredlevel` = '30' WHERE `entry` = '8629';
UPDATE `items` SET `requiredlevel` = '30' WHERE `entry` = '13322';
UPDATE `items` SET `requiredlevel` = '30' WHERE `entry` = '8588';
UPDATE `items` SET `requiredlevel` = '30' WHERE `entry` = '8591';
UPDATE `items` SET `requiredlevel` = '30' WHERE `entry` = '8592';
UPDATE `items` SET `requiredlevel` = '30' WHERE `entry` = '5873';
UPDATE `items` SET `requiredlevel` = '30' WHERE `entry` = '8628';
UPDATE `items` SET `requiredlevel` = '30' WHERE `entry` = '29221';
UPDATE `items` SET `requiredlevel` = '30' WHERE `entry` = '2411';
UPDATE `items` SET `requiredlevel` = '30' WHERE `entry` = '29220';
UPDATE `items` SET `requiredlevel` = '30' WHERE `entry` = '8595';
UPDATE `items` SET `requiredlevel` = '30' WHERE `entry` = '13332';
UPDATE `items` SET `requiredlevel` = '30' WHERE `entry` = '33976';
UPDATE `items` SET `requiredlevel` = '30' WHERE `entry` = '28481';
UPDATE `items` SET `requiredlevel` = '30' WHERE `entry` = '5656';
UPDATE `items` SET `requiredlevel` = '30' WHERE `entry` = '15290';
UPDATE `items` SET `requiredlevel` = '30' WHERE `entry` = '5872';
UPDATE `items` SET `requiredlevel` = '30' WHERE `entry` = '13333';
UPDATE `items` SET `requiredlevel` = '30' WHERE `entry` = '5655';
UPDATE `items` SET `requiredlevel` = '30' WHERE `entry` = '29744';
UPDATE `items` SET `requiredlevel` = '30' WHERE `entry` = '15277';
UPDATE `items` SET `requiredlevel` = '30' WHERE `entry` = '5864';
UPDATE `items` SET `requiredlevel` = '30' WHERE `entry` = '13321';
UPDATE `items` SET `requiredlevel` = '30' WHERE `entry` = '5668';
UPDATE `items` SET `requiredlevel` = '30' WHERE `entry` = '5665';

UPDATE items SET `requiredlevel` = '30' WHERE `RequiredSkill` = '762' AND `RequiredSkillRank` ='75';
UPDATE `trainer_spells` SET `reqlevel`=30, `spellcost`=350000 WHERE `learn_spell` = 33388;
UPDATE `trainer_spells` SET `reqlevel`=30 WHERE `learn_spell` = 5784 OR `learn_spell` = 13819 OR `learn_spell` = 34769; 